### ISSUE TITLE
Adding space on the theme page 

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/riverbank#12]
Hi there!

Can we add an extra space after this section? Right now it looks as if it cuts the images:
<img width="912" alt="image" src="https://user-images.githubusercontent.com/86592992/215145935-2da1794d-0069-429a-b487-285bab300904.png">

Also, I think there is a missing dot at the end of the description ( under Elegant, etc ).

**Comment by HardeepAsrani** [comment]
@AndreeaCristinaRadacina I think that's how the design was made to look with the image coming from the container, adding space there will make it look weird.

**Comment by mghenciu** [comment]
Will close this, as this was an intended Design choice.
