### ISSUE TITLE
Buttons in Row blocks

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/riverbank#4]
@abaicus I was wondering if you have some insights with an issue I am facing with buttons, when they are used inside a row.

When in mobile view, looks like that the button's width is not maintained, instead it is getting squeezed:

![Screenshot 2022-12-07 at 3 45 36 PM](https://user-images.githubusercontent.com/4193672/206196825-e52c4078-6947-4bbf-a859-a6157048edaf.png)

You can see it live [at the taste instance](https://heavenlymagic.s4-tastewp.com/) at the homepage (right below the hero section). Anything we should add in the button's CSS or I should look into using columns instead of rows?

Thanks in advance!

**Comment by abaicus** [comment]
@JohnPixle That's how core treats rows and groups (flex containers). 

There's not much we can do to the button except add a `flex-shrink: 0;` to all buttons inside a row component, but I am not sure if that would act fine in all contexts. 

e.g., Otter button block would yield the same issue:

![image](https://user-images.githubusercontent.com/15010186/206210999-15e5c7d5-7a56-4241-841e-f801f29afd3f.png)

We can try looking into the flex-wrap option if that does anything good. This is markup and style generated by core, and changing it might break some things in other contexts, so I'm weary to do it. 

![image](https://user-images.githubusercontent.com/15010186/206208924-582e49a7-8c7a-4adb-89b8-537d124e5f5a.png)
