### ISSUE TITLE
Different font sizes in FSE Editor and in frontend

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/riverbank#5]
@abaicus One last thing I noticed is that in the FSE editor, the font sizes are a bit smaller than what they are at the frontend. 

![Screenshot 2022-12-07 at 3 57 37 PM](https://user-images.githubusercontent.com/4193672/206198353-cfcdba9d-8a31-4efa-bd8b-608dec349358.png)

![Screenshot 2022-12-07 at 3 57 41 PM](https://user-images.githubusercontent.com/4193672/206198370-da67ee9b-39e7-4cfd-b140-f7737ba94d94.png)

This happens only in the context of the FSE editor, the font sizes are ok when editing a page.

In case you need to take a look:

```
 Admin area URL: https://heavenlymagic.s4-tastewp.com/wp-admin 
 Username: pixle 
 Password: 4ZNathNv24E 
```

**Comment by abaicus** [comment]
@JohnPixle This doesn't happen locally on a WP Instance. I think there might be some things that work different in the context of TasteWP.

**Comment by abaicus** [comment]
Here's a screenshot of the frontend over-imposed and inverted above the editor content from my local instance: 
![image](https://user-images.githubusercontent.com/15010186/206201676-91bad8fa-ec41-4aa1-b740-a10433586b47.png)
