### ISSUE TITLE
Update image urls in frontpage

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/riverbank#6]
@abaicus As discussed in Slack, I updated the front page template, but the images need to be replaced with their proper urls.

demo: https://heavenlymagic.s4-tastewp.com/

Let me know if I can help with anything.

**Comment by abaicus** [comment]
@JohnPixle We should add the frontpage patterns that contain images as patterns into the theme as well. Otherwise, we'd have no way to add proper links for the images. 

I can extract all the sections from the site and move them to patterns 🚀
